/* ==========================================================================
   Themenpool für das erste und zweite juristische Staatsexamen.

   Zuschnitt: Der Pool ist aus den bestehenden Beiträgen des Kanals abgeleitet
   – Frage-zuerst, Abgrenzungen, Definitionen, Streitstände, Meinungsstreit.
   Nicht Lehrbuch, sondern das, was in der Klausur den Unterschied macht.

   Ein Eintrag ist bewusst schlank: Titel (die Frage), die tragenden Normen,
   Examenspriorität und ein paar Stichpunkte als Gedankenstütze. Ausformuliert
   wird nichts – das macht der Autor (autor.mjs), und der Faktencheck prüft
   nach. So bleibt der Pool wartbar und der Beitrag klingt nie nach Datenbank.

   prioritaet: hoch = Dauerbrenner, mittel = regelmäßig, selten = Nische mit
   Aufmerksamkeitswert.
   ========================================================================== */

export const THEMEN = [
  /* ---- Zivilrecht: BGB AT ------------------------------------------------ */
  { fach: "bgbat", titel: "Was sind die Voraussetzungen und Rechtsfolgen einer wirksamen Anfechtung?", normen: ["§ 119 BGB", "§ 123 BGB", "§ 142 Abs. 1 BGB", "§ 143 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Anfechtungsgrund, Erklärung, Frist, Anfechtungsgegner", "Rückwirkende Nichtigkeit und § 122 BGB als Kehrseite"], pruefschritte: ["Anfechtbare Willenserklärung", "Anfechtungsgrund", "Anfechtungserklärung gegenüber dem richtigen Gegner", "Frist", "Kein Ausschluss"] } },
  { fach: "bgbat", titel: "Wie erfolgt die Abgrenzung zwischen Vertrag und Gefälligkeit?", normen: ["§ 145 BGB", "§ 241 Abs. 1 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Rechtsbindungswille als objektiver Maßstab", "Gefälligkeitsverhältnis mit rechtlichem Charakter als Zwischenstufe"] } },
  { fach: "bgbat", titel: "Inwieweit werden sich widersprechende AGB Vertragsbestandteil?", normen: ["§ 305 Abs. 2 BGB", "§ 306 BGB", "§ 154 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Theorie des letzten Wortes gegen Restgültigkeitstheorie", "Herrschend: kongruente Klauseln gelten, der Rest fällt weg"] } },
  { fach: "bgbat", titel: "Welche Formvorschriften gibt es und was ist die Folge eines Formverstoßes?", normen: ["§ 125 BGB", "§ 126 BGB", "§ 126a BGB", "§ 126b BGB", "§ 128 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was besagt die Kipp'sche Lehre von der Doppelnichtigkeit?", normen: ["§ 134 BGB", "§ 138 BGB", "§ 142 BGB"], prioritaet: "selten" },
  { fach: "bgbat", titel: "Wie wirkt die Stellvertretung ohne Vertretungsmacht?", normen: ["§ 177 BGB", "§ 179 BGB", "§ 164 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wann liegt ein Insichgeschäft vor und wann ist es zulässig?", normen: ["§ 181 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Worin unterscheiden sich Anfechtung und Wegfall der Geschäftsgrundlage?", normen: ["§ 119 Abs. 2 BGB", "§ 313 BGB"], prioritaet: "hoch" },

  /* ---- Zivilrecht: Schuldrecht AT ---------------------------------------- */
  { fach: "schuld", titel: "Welche Arten der Leistungsstörung gibt es?", normen: ["§ 275 BGB", "§ 280 BGB", "§ 286 BGB", "§ 323 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Unmöglichkeit, Verzug, Schlechtleistung, Nebenpflichtverletzung", "Immer zuerst: Welcher Anspruch, welche Pflicht, welche Störung?"] } },
  { fach: "schuld", titel: "Wann liegt Annahmeverzug vor?", normen: ["§ 293 BGB", "§ 294 BGB", "§ 295 BGB", "§ 296 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was sind die Rechtsfolgen des Annahmeverzugs?", normen: ["§ 300 BGB", "§ 301 BGB", "§ 302 BGB", "§ 304 BGB", "§ 326 Abs. 2 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was ist der Unterschied zwischen dem Schuldner- und dem Gläubigerverzug?", normen: ["§ 286 BGB", "§ 293 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann tritt Konkretisierung bei Hol-, Bring- und Schickschulden ein?", normen: ["§ 243 Abs. 2 BGB", "§ 269 BGB", "§ 447 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Konkretisierung setzt das zur Leistung Erforderliche voraus", "Bei der Schickschuld: Übergabe an die Transportperson"] } },
  { fach: "schuld", titel: "Was ist der Unterschied zwischen dem Ersatz des positiven und des negativen Interesses?", normen: ["§ 249 BGB", "§ 122 BGB", "§ 284 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was besagt die Lehre vom fehlerhaften Vertrag?", normen: ["§ 142 BGB", "§ 611a BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Wann haftet man für das Verschulden eines Erfüllungsgehilfen?", normen: ["§ 278 BGB", "§ 831 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wie prüft man einen Anspruch aus culpa in contrahendo?", normen: ["§ 311 Abs. 2 BGB", "§ 241 Abs. 2 BGB", "§ 280 Abs. 1 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was besagt die Saldotheorie?", normen: ["§ 812 BGB", "§ 818 Abs. 3 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann ist ein Vertrag zugunsten Dritter echt und wann unecht?", normen: ["§ 328 BGB", "§ 329 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Was ist ein Vertrag mit Schutzwirkung zugunsten Dritter?", normen: ["§ 311 Abs. 3 BGB", "§ 328 BGB"], prioritaet: "hoch" },

  /* ---- Zivilrecht: Schuldrecht BT ---------------------------------------- */
  { fach: "schuldbt", titel: "Welche Kaufarten sind im BGB geregelt?", normen: ["§ 433 BGB", "§ 453 BGB", "§ 474 BGB", "§ 481 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Wie ist der geminderte Kaufpreis nach § 441 Abs. 3 BGB zu berechnen?", normen: ["§ 441 Abs. 3 BGB", "§ 437 Nr. 2 BGB"], prioritaet: "mittel",
    kern: { lernziele: ["Verhältnisrechnung: Kaufpreis mal Istwert geteilt durch Sollwert", "Nicht der Mangelbeseitigungsaufwand ist der Maßstab"] } },
  { fach: "schuldbt", titel: "Wie werden Dienst- und Werkvertrag voneinander abgegrenzt?", normen: ["§ 611 BGB", "§ 631 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wann kann der Käufer ohne Fristsetzung zurücktreten?", normen: ["§ 323 Abs. 2 BGB", "§ 440 BGB", "§ 326 Abs. 5 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Was gilt beim Verbrauchsgüterkauf anders?", normen: ["§ 474 BGB", "§ 475 BGB", "§ 477 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Ist Vertragspartner des Anwalts stets der Mandant?", normen: ["§ 675 BGB", "§ 611 BGB"], prioritaet: "selten" },
  { fach: "schuldbt", titel: "Lohnt sich ein langjähriger Ratenkauf?", normen: ["§ 491 BGB", "§ 355 BGB"], prioritaet: "selten" },

  /* ---- Zivilrecht: Sachenrecht ------------------------------------------- */
  { fach: "sachen", titel: "Welche Vermutungen enthält § 1006 BGB?", normen: ["§ 1006 BGB", "§ 985 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Welche dinglichen Rechte gibt es?", normen: ["§ 903 BGB", "§ 1018 BGB", "§ 1113 BGB", "§ 1204 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Welche Ausnahmen gibt es zur Sperrwirkung des EBV im Deliktsrecht?", normen: ["§ 993 Abs. 1 BGB", "§ 992 BGB", "§ 823 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Nicht-so-berechtigter Besitzer, Fremdbesitzerexzess, deliktischer Besitzerwerb"] } },
  { fach: "sachen", titel: "Wann ist ein gutgläubiger Erwerb ausgeschlossen?", normen: ["§ 932 BGB", "§ 935 BGB", "§ 936 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie funktioniert das Anwartschaftsrecht beim Eigentumsvorbehalt?", normen: ["§ 449 BGB", "§ 929 BGB", "§ 158 Abs. 1 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie prüft man den Herausgabeanspruch aus § 985 BGB?", normen: ["§ 985 BGB", "§ 986 BGB"], prioritaet: "hoch" },

  /* ---- Zivilrecht: Deliktsrecht ------------------------------------------ */
  { fach: "delikt", titel: "Trifft Fahrradfahrer ein Mitverschulden bei fehlendem Helm?", normen: ["§ 254 BGB", "§ 823 Abs. 1 BGB"], prioritaet: "selten" },
  { fach: "delikt", titel: "Wann haftet der Geschäftsherr nach § 831 BGB und wann kann er sich entlasten?", normen: ["§ 831 BGB", "§ 278 BGB"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Was ist das Recht am eingerichteten und ausgeübten Gewerbebetrieb?", normen: ["§ 823 Abs. 1 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wie prüft man die Verkehrssicherungspflicht?", normen: ["§ 823 Abs. 1 BGB"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Wann greift die Produzentenhaftung neben dem ProdHaftG?", normen: ["§ 823 Abs. 1 BGB", "§ 1 ProdHaftG"], prioritaet: "mittel" },

  /* ---- Zivilrecht: Arbeitsrecht ------------------------------------------ */
  { fach: "arbeit", titel: "Was sind die wichtigsten Rechtsfolgen einer Schwangerschaft im Arbeitsrecht?", normen: ["§ 17 MuSchG", "§ 3 MuSchG", "§ 15 BEEG"], prioritaet: "mittel" },
  { fach: "arbeit", titel: "Wie prüft man die Wirksamkeit einer ordentlichen Kündigung?", normen: ["§ 1 KSchG", "§ 623 BGB", "§ 102 BetrVG"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wann ist eine außerordentliche Kündigung gerechtfertigt?", normen: ["§ 626 BGB"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wie grenzt man Arbeitnehmer und freien Mitarbeiter ab?", normen: ["§ 611a BGB"], prioritaet: "hoch" },

  /* ---- Zivilrecht: Familien- und Erbrecht -------------------------------- */
  { fach: "famerb", titel: "Was bedeutet „angemessen“ i.S.d. § 1357 BGB?", normen: ["§ 1357 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Müssen Kinder im Haushalt helfen?", normen: ["§ 1619 BGB"], prioritaet: "selten" },
  { fach: "famerb", titel: "Wie wird der Pflichtteil berechnet?", normen: ["§ 2303 BGB", "§ 2311 BGB", "§ 2325 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Worin unterscheiden sich Vor- und Nacherbe von Erbe und Vermächtnisnehmer?", normen: ["§ 2100 BGB", "§ 1939 BGB", "§ 2174 BGB"], prioritaet: "mittel" },

  /* ---- Zivilrecht: Handels- und Gesellschaftsrecht ------------------------ */
  { fach: "handelsg", titel: "Wann liegt ein Handelsgeschäft vor und was folgt daraus?", normen: ["§ 343 HGB", "§ 377 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie haftet der Gesellschafter einer GbR nach der Reform?", normen: ["§ 721 BGB", "§ 128 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Was ist die Rechtsscheinhaftung im Handelsrecht?", normen: ["§ 5 HGB", "§ 15 HGB"], prioritaet: "mittel" },

  /* ---- Zivilrecht: ZPO --------------------------------------------------- */
  { fach: "zpo", titel: "Was bedeuten Anhängigkeit und Rechtshängigkeit?", normen: ["§ 253 Abs. 1 ZPO", "§ 261 ZPO", "§ 262 ZPO"], prioritaet: "hoch",
    kern: { lernziele: ["Anhängigkeit ab Einreichung, Rechtshängigkeit ab Zustellung", "Rechtsfolgen: Verjährungshemmung, Verbot doppelter Rechtshängigkeit"] } },
  { fach: "zpo", titel: "Worauf kommt es für den rechtzeitigen Eingang eines per Telefax übermittelten Schriftsatzes bei Gericht an?", normen: ["§ 130 ZPO", "§ 130a ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Was sind die allgemeinen Voraussetzungen der Zwangsvollstreckung?", normen: ["§ 704 ZPO", "§ 750 ZPO", "§ 794 ZPO"], prioritaet: "hoch",
    kern: { lernziele: ["Titel, Klausel, Zustellung als Dreiklang"] } },
  { fach: "zpo", titel: "Was sind die Voraussetzungen eines Versäumnisurteils gegen den Beklagten?", normen: ["§ 331 ZPO", "§ 335 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wie ist der Instanzenzug im Zivilprozess?", normen: ["§ 511 ZPO", "§ 542 ZPO", "§ 23 GVG", "§ 71 GVG"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wie unterscheiden sich Leistungs-, Feststellungs- und Gestaltungsklage?", normen: ["§ 253 ZPO", "§ 256 ZPO"], prioritaet: "hoch" },

  /* ---- Strafrecht AT ------------------------------------------------------ */
  { fach: "strafat", titel: "Was ist der Unterschied zwischen Eventualvorsatz und bewusster Fahrlässigkeit?", normen: ["§ 15 StGB", "§ 16 StGB"], prioritaet: "hoch",
    kern: { lernziele: ["Wissens- und Wollenselement", "Billigend in Kauf nehmen gegen pflichtwidriges Vertrauen"] } },
  { fach: "strafat", titel: "Welche Arten der Kausalität gibt es?", normen: ["§ 13 StGB"], prioritaet: "hoch",
    kern: { lernziele: ["Äquivalenz, kumulativ, alternativ, abgebrochen, überholend", "Objektive Zurechnung als Korrektiv"] } },
  { fach: "strafat", titel: "Was ist ein untauglicher Versuch, was ein Wahndelikt?", normen: ["§ 22 StGB", "§ 23 Abs. 3 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist ein intensiver bzw. extensiver Notwehrexzess?", normen: ["§ 33 StGB", "§ 32 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Worin unterscheiden sich Einverständnis und Einwilligung?", normen: ["§ 228 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Worin unterscheiden sich Beschützer- und Überwachergarant?", normen: ["§ 13 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wann ist ein Rücktritt vom Versuch strafbefreiend?", normen: ["§ 24 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie grenzt man Täterschaft und Teilnahme ab?", normen: ["§ 25 StGB", "§ 26 StGB", "§ 27 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist der Erlaubnistatbestandsirrtum und wie wird er behandelt?", normen: ["§ 16 StGB", "§ 17 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man die actio libera in causa?", normen: ["§ 20 StGB", "§ 323a StGB"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Welche BAK-Grenzwerte muss man kennen?", normen: ["§ 20 StGB", "§ 21 StGB", "§ 316 StGB"], prioritaet: "mittel" },

  /* ---- Strafrecht BT ------------------------------------------------------ */
  { fach: "strafbt", titel: "Wie ist das Verhältnis zwischen § 211 StGB und § 212 StGB?", normen: ["§ 211 StGB", "§ 212 StGB", "§ 28 StGB"], prioritaet: "hoch",
    kern: { lernziele: ["Rechtsprechung: eigenständiger Tatbestand", "Literatur: Qualifikation – Folgen für § 28 StGB"] } },
  { fach: "strafbt", titel: "Wann liegt Heimtücke vor?", normen: ["§ 211 Abs. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie grenzt man Diebstahl und Betrug ab?", normen: ["§ 242 StGB", "§ 263 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann liegt eine Zueignungsabsicht vor?", normen: ["§ 242 StGB", "§ 246 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man den Vermögensschaden beim Betrug?", normen: ["§ 263 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist Raub vollendet und wie verhält er sich zur räuberischen Erpressung?", normen: ["§ 249 StGB", "§ 253 StGB", "§ 255 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist eine gefährliche Körperverletzung nach § 224 StGB?", normen: ["§ 223 StGB", "§ 224 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Ist die Bezeichnung „Bulle“ gegenüber einem Polizisten strafbar?", normen: ["§ 185 StGB"], prioritaet: "selten" },

  /* ---- Strafprozessrecht -------------------------------------------------- */
  { fach: "stpo", titel: "Welche Beweisverwertungsverbote gibt es und wie prüft man sie?", normen: ["§ 136a StPO", "§ 100a StPO"], prioritaet: "hoch" },
  { fach: "stpo", titel: "Wann darf ohne richterliche Anordnung durchsucht werden?", normen: ["§ 102 StPO", "§ 105 StPO", "Art. 13 GG"], prioritaet: "hoch" },
  { fach: "stpo", titel: "Was sind die Voraussetzungen der Untersuchungshaft?", normen: ["§ 112 StPO", "§ 116 StPO"], prioritaet: "mittel" },

  /* ---- Öffentliches Recht: Staatsrecht ------------------------------------ */
  { fach: "staat", titel: "Was sind die wichtigsten Ausprägungen des Rechtsstaatsprinzips?", normen: ["Art. 20 Abs. 3 GG", "Art. 19 Abs. 4 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Welche Form von Demokratie sieht das Grundgesetz vor?", normen: ["Art. 20 Abs. 2 GG", "Art. 38 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Wie lauten die Wahlgrundsätze und welche Bedeutung haben sie?", normen: ["Art. 38 Abs. 1 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Welche Rechte und Pflichten hat der Bundespräsident?", normen: ["Art. 54 GG", "Art. 82 GG", "Art. 60 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Worin unterscheiden sich echte und unechte Rückwirkung?", normen: ["Art. 20 Abs. 3 GG", "Art. 2 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Welche Bedeutung hat die Radbruch'sche Formel?", normen: ["Art. 20 Abs. 3 GG"], prioritaet: "selten" },
  { fach: "staat", titel: "Welche Gerichtsbarkeiten gibt es in Deutschland?", normen: ["Art. 95 GG", "Art. 92 GG"], prioritaet: "selten" },
  { fach: "staat", titel: "Wann gelten Vorrang und Vorbehalt des Gesetzes?", normen: ["Art. 20 Abs. 3 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wie prüft man die Verfassungsbeschwerde?", normen: ["Art. 93 Abs. 1 Nr. 4a GG", "§ 90 BVerfGG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wann hat der Bund die Gesetzgebungskompetenz?", normen: ["Art. 70 GG", "Art. 72 GG", "Art. 74 GG"], prioritaet: "hoch" },

  /* ---- Öffentliches Recht: Grundrechte ------------------------------------ */
  { fach: "grundr", titel: "Wie prüft man einen Eingriff in Art. 12 GG?", normen: ["Art. 12 Abs. 1 GG"], prioritaet: "hoch",
    kern: { lernziele: ["Drei-Stufen-Theorie", "Abgrenzung zu Art. 14 GG: erwerben gegen erworben"] } },
  { fach: "grundr", titel: "Wann ist Art. 2 Abs. 1 GG einschlägig und wann ein spezielleres Grundrecht?", normen: ["Art. 2 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie wirken Grundrechte zwischen Privaten?", normen: ["Art. 1 Abs. 3 GG", "§ 242 BGB"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie prüft man die Verhältnismäßigkeit?", normen: ["Art. 20 Abs. 3 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Was schützt die allgemeine Handlungsfreiheit nicht mehr?", normen: ["Art. 2 Abs. 1 GG", "Art. 2 Abs. 2 GG"], prioritaet: "mittel" },

  /* ---- Öffentliches Recht: Verwaltungsrecht ------------------------------- */
  { fach: "verwalt", titel: "Was ist der Unterschied zwischen Entschließungs- und Auswahlermessen?", normen: ["§ 40 VwVfG", "§ 114 VwGO"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Was ist ein Koordinations- und was ein Subordinationsvertrag i.S.d. §§ 54 ff. VwVfG?", normen: ["§ 54 VwVfG", "§ 55 VwVfG", "§ 56 VwVfG"], prioritaet: "mittel" },
  { fach: "verwalt", titel: "Welche Arten von Verwaltungsvorschriften gibt es?", normen: ["Art. 84 Abs. 2 GG", "§ 40 VwVfG"], prioritaet: "mittel" },
  { fach: "verwalt", titel: "Wann ist ein Verwaltungsakt nichtig?", normen: ["§ 44 VwVfG", "§ 43 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann darf ein rechtswidriger begünstigender Verwaltungsakt zurückgenommen werden?", normen: ["§ 48 VwVfG", "§ 49 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wie prüft man die Bestimmtheit eines Verwaltungsakts?", normen: ["§ 37 VwVfG", "§ 35 VwVfG"], prioritaet: "mittel" },
  { fach: "verwalt", titel: "Welche Arten von Gemeindehoheiten gibt es?", normen: ["Art. 28 Abs. 2 GG"], prioritaet: "mittel" },

  /* ---- Öffentliches Recht: Verwaltungsprozessrecht ------------------------ */
  { fach: "vwgo", titel: "Welche Formen einer einstweiligen Anordnung gibt es nach § 123 Abs. 1 VwGO?", normen: ["§ 123 Abs. 1 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wann wendet man § 123 VwGO und wann § 80 Abs. 5 VwGO im einstweiligen Rechtsschutz an?", normen: ["§ 123 Abs. 5 VwGO", "§ 80 Abs. 5 VwGO"], prioritaet: "hoch",
    kern: { lernziele: ["Faustformel: Belastender VA angegriffen → § 80 Abs. 5 VwGO", "Alles andere → § 123 VwGO"] } },
  { fach: "vwgo", titel: "Wie prüft man die Zulässigkeit der Anfechtungsklage?", normen: ["§ 42 Abs. 1 VwGO", "§ 42 Abs. 2 VwGO", "§ 68 VwGO", "§ 74 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wann ist die Fortsetzungsfeststellungsklage statthaft?", normen: ["§ 113 Abs. 1 S. 4 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wie grenzt man Verpflichtungs- und allgemeine Leistungsklage ab?", normen: ["§ 42 Abs. 1 VwGO", "§ 43 VwGO"], prioritaet: "hoch" },

  /* ---- Öffentliches Recht: Europarecht ------------------------------------ */
  { fach: "europa", titel: "Welches sind die vier EU-Grundfreiheiten?", normen: ["Art. 34 AEUV", "Art. 45 AEUV", "Art. 49 AEUV", "Art. 56 AEUV", "Art. 63 AEUV"], prioritaet: "mittel" },
  { fach: "europa", titel: "Welche Organe hat die EU?", normen: ["Art. 13 EUV"], prioritaet: "mittel" },
  { fach: "europa", titel: "Wann wirkt eine Richtlinie unmittelbar?", normen: ["Art. 288 AEUV"], prioritaet: "hoch" },
  { fach: "europa", titel: "Was ist das Vorabentscheidungsverfahren?", normen: ["Art. 267 AEUV"], prioritaet: "hoch" },

  /* ---- Öffentliches Recht: Besonderes Verwaltungsrecht ------------------- */
  { fach: "verwbt", titel: "Wie prüft man die Rechtmäßigkeit einer Baugenehmigung?", normen: ["§ 29 BauGB", "§ 30 BauGB", "§ 34 BauGB", "§ 35 BauGB"], prioritaet: "hoch",
    kern: { lernziele: ["Erst die Zulässigkeit nach Planungsrecht, dann das Bauordnungsrecht des Landes", "Innenbereich, Außenbereich, Bebauungsplan – die drei Weichen"] } },
  { fach: "verwbt", titel: "Wann ist ein Vorhaben im Außenbereich zulässig?", normen: ["§ 35 Abs. 1 BauGB", "§ 35 Abs. 2 BauGB"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Was ist das Gebot der Rücksichtnahme?", normen: ["§ 15 BauNVO", "§ 34 Abs. 1 BauGB"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wer ist Störer im Polizei- und Ordnungsrecht?", normen: ["Polizeigesetze der Länder"], prioritaet: "hoch",
    kern: { lernziele: ["Handlungsstörer, Zustandsstörer, Nichtstörer", "Unmittelbarkeitstheorie gegen Theorie der rechtswidrigen Verursachung"] } },
  { fach: "verwbt", titel: "Wann darf die Polizei einen Nichtstörer in Anspruch nehmen?", normen: ["Polizeigesetze der Länder"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Was ist der Unterschied zwischen Gefahr, Anscheinsgefahr und Gefahrenverdacht?", normen: ["Polizeigesetze der Länder"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wie prüft man die Rechtmäßigkeit einer kommunalen Satzung?", normen: ["Art. 28 Abs. 2 GG", "Gemeindeordnungen der Länder"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Wann hat ein Gemeinderatsmitglied ein Mitwirkungsverbot?", normen: ["Gemeindeordnungen der Länder"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Was ist eine öffentliche Einrichtung und wer hat Zugang zu ihr?", normen: ["Art. 28 Abs. 2 GG", "Gemeindeordnungen der Länder"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Wie ist der Verwaltungszwang aufgebaut?", normen: ["§ 6 VwVG", "§ 13 VwVG"], prioritaet: "hoch" },

  /* ---- Weitere Dauerbrenner ---------------------------------------------- */
  { fach: "bgbat", titel: "Wann ist ein Schweigen als Willenserklärung zu werten?", normen: ["§ 151 BGB", "§ 362 HGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was gilt beim Handeln unter fremdem Namen?", normen: ["§ 164 BGB", "§ 177 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Wie prüft man den Rücktritt nach § 323 BGB?", normen: ["§ 323 BGB", "§ 346 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was ist die Drittschadensliquidation und wann greift sie?", normen: ["§ 249 BGB", "§ 447 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Zufällige Schadensverlagerung als Voraussetzung", "Fallgruppen: mittelbare Stellvertretung, Obhutsfälle, Versendungskauf"] } },
  { fach: "schuldbt", titel: "Wie grenzt man Miete und Leihe ab?", normen: ["§ 535 BGB", "§ 598 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Wann haftet der Bürge und wann kann er die Einrede erheben?", normen: ["§ 765 BGB", "§ 768 BGB", "§ 771 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wie prüft man die Sicherungsübereignung?", normen: ["§ 930 BGB", "§ 868 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Was ist ein Scheinbestandteil und was ein wesentlicher Bestandteil?", normen: ["§ 93 BGB", "§ 94 BGB", "§ 95 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wie wird das allgemeine Persönlichkeitsrecht geschützt?", normen: ["§ 823 Abs. 1 BGB", "Art. 2 Abs. 1 GG", "Art. 1 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wann ist eine Klageänderung zulässig?", normen: ["§ 263 ZPO", "§ 264 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wie funktioniert die Drittwiderspruchsklage?", normen: ["§ 771 ZPO"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man den rechtfertigenden Notstand?", normen: ["§ 34 StGB", "§ 228 BGB", "§ 904 BGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist ein error in persona und wie wirkt die aberratio ictus?", normen: ["§ 16 StGB"], prioritaet: "hoch",
    kern: { lernziele: ["Rechtsprechung: aberratio ictus meist unbeachtlich bei Gleichwertigkeit", "Literatur: Konkretisierung entscheidet – Versuch plus Fahrlässigkeit"] } },
  { fach: "strafat", titel: "Wann ist der Versuch beendet und wann unbeendet?", normen: ["§ 24 Abs. 1 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man die Untreue nach § 266 StGB?", normen: ["§ 266 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann liegt eine Urkundenfälschung vor?", normen: ["§ 267 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist der Unterschied zwischen Raub und räuberischem Diebstahl?", normen: ["§ 249 StGB", "§ 252 StGB"], prioritaet: "hoch" },
  { fach: "stpo", titel: "Wie ist der Ablauf einer Hauptverhandlung?", normen: ["§ 243 StPO", "§ 244 StPO", "§ 258 StPO"], prioritaet: "mittel" },
  { fach: "staat", titel: "Wie prüft man das Organstreitverfahren?", normen: ["Art. 93 Abs. 1 Nr. 1 GG", "§ 63 BVerfGG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wann ist die Meinungsfreiheit eingeschränkt?", normen: ["Art. 5 Abs. 1 GG", "Art. 5 Abs. 2 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie prüft man den allgemeinen Gleichheitssatz?", normen: ["Art. 3 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann liegt ein Verwaltungsakt vor?", normen: ["§ 35 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Was ist eine Allgemeinverfügung?", normen: ["§ 35 S. 2 VwVfG"], prioritaet: "mittel" },
  { fach: "vwgo", titel: "Wann ist die Feststellungsklage subsidiär?", normen: ["§ 43 Abs. 2 VwGO"], prioritaet: "mittel" },
  { fach: "europa", titel: "Wie prüft man einen Verstoß gegen die Warenverkehrsfreiheit?", normen: ["Art. 34 AEUV", "Art. 36 AEUV"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wann ist ein Betriebsübergang nach § 613a BGB gegeben?", normen: ["§ 613a BGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie haftet der eintretende Gesellschafter für Altschulden?", normen: ["§ 721a BGB", "§ 130 HGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wie funktioniert der Zugewinnausgleich?", normen: ["§ 1373 BGB", "§ 1378 BGB"], prioritaet: "mittel" },

  /* ======================================================================
     Erweiterung: systematisch nach dem Pflichtfachkatalog. Zivilrecht.
     ====================================================================== */

  /* ---- BGB AT ------------------------------------------------------------ */
  { fach: "bgbat", titel: "Wann geht eine Willenserklärung unter Abwesenden zu?", normen: ["§ 130 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Was gilt, wenn der Zugang einer Willenserklärung vereitelt wird?", normen: ["§ 130 BGB", "§ 242 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Wie grenzt man Angebot und invitatio ad offerendum ab?", normen: ["§ 145 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wie kommt ein Vertrag bei einer Internetauktion zustande?", normen: ["§ 145 BGB", "§ 156 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was ist ein versteckter und was ein offener Dissens?", normen: ["§ 154 BGB", "§ 155 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Wie wirkt sich beschränkte Geschäftsfähigkeit auf einen Vertrag aus?", normen: ["§ 107 BGB", "§ 108 BGB", "§ 110 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Was ist ein lediglich rechtlicher Vorteil i.S.d. § 107 BGB?", normen: ["§ 107 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wann ist ein Rechtsgeschäft sittenwidrig?", normen: ["§ 138 Abs. 1 BGB", "§ 138 Abs. 2 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wann liegt ein wucherähnliches Geschäft vor?", normen: ["§ 138 Abs. 1 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was ist der Unterschied zwischen Nichtigkeit und schwebender Unwirksamkeit?", normen: ["§ 134 BGB", "§ 108 BGB", "§ 177 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Wie wirkt § 139 BGB bei Teilnichtigkeit?", normen: ["§ 139 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was ist eine geltungserhaltende Reduktion und warum ist sie bei AGB unzulässig?", normen: ["§ 306 BGB", "§ 307 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wie prüft man die Duldungs- und die Anscheinsvollmacht?", normen: ["§ 167 BGB", "§ 172 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Duldungsvollmacht: Vertretener kennt und lässt gewähren", "Anscheinsvollmacht: er hätte es erkennen können – Streit um die Rechtsfolge"] } },
  { fach: "bgbat", titel: "Was ist Missbrauch der Vertretungsmacht?", normen: ["§ 164 BGB", "§ 242 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Wie unterscheidet man Boten und Stellvertreter?", normen: ["§ 164 BGB", "§ 120 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Wann beginnt die regelmäßige Verjährung und wann endet sie?", normen: ["§ 195 BGB", "§ 199 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Wie wirken Hemmung, Ablaufhemmung und Neubeginn der Verjährung?", normen: ["§ 203 BGB", "§ 204 BGB", "§ 212 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Was ist der Unterschied zwischen Anfechtung und arglistiger Täuschung durch Dritte?", normen: ["§ 123 Abs. 2 BGB"], prioritaet: "mittel" },
  { fach: "bgbat", titel: "Ist der Eigenschaftsirrtum ein Motivirrtum?", normen: ["§ 119 Abs. 2 BGB"], prioritaet: "hoch" },
  { fach: "bgbat", titel: "Was ist ein Kalkulationsirrtum und ist er beachtlich?", normen: ["§ 119 BGB", "§ 242 BGB"], prioritaet: "mittel" },

  /* ---- Schuldrecht AT ---------------------------------------------------- */
  { fach: "schuld", titel: "Wie prüft man einen Schadensersatzanspruch statt der Leistung?", normen: ["§ 280 Abs. 1 BGB", "§ 280 Abs. 3 BGB", "§ 281 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann ist eine Fristsetzung entbehrlich?", normen: ["§ 281 Abs. 2 BGB", "§ 323 Abs. 2 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was ist der Unterschied zwischen Unmöglichkeit und Unzumutbarkeit?", normen: ["§ 275 Abs. 1 BGB", "§ 275 Abs. 2 BGB", "§ 275 Abs. 3 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wer trägt die Gegenleistungsgefahr bei Unmöglichkeit?", normen: ["§ 326 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann haftet der Schuldner nur für eigenübliche Sorgfalt?", normen: ["§ 277 BGB", "§ 690 BGB"], prioritaet: "selten" },
  { fach: "schuld", titel: "Wie berechnet man den Schadensersatz nach der Differenzhypothese?", normen: ["§ 249 BGB", "§ 252 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann ist ein Schaden normativ zu korrigieren?", normen: ["§ 249 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Wie prüft man die Vorteilsausgleichung?", normen: ["§ 249 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Was ersetzt § 251 BGB und wann greift er statt § 249 BGB?", normen: ["§ 249 BGB", "§ 251 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Wann ist ein Mitverschulden zu berücksichtigen?", normen: ["§ 254 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wie funktioniert die Abtretung und was sind ihre Grenzen?", normen: ["§ 398 BGB", "§ 399 BGB", "§ 404 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Was ist eine Schuldübernahme und was ein Schuldbeitritt?", normen: ["§ 414 BGB", "§ 415 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Wie wirkt die Gesamtschuld im Innen- und im Außenverhältnis?", normen: ["§ 421 BGB", "§ 426 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann ist eine AGB-Klausel überraschend?", normen: ["§ 305c BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wie prüft man die Inhaltskontrolle von AGB?", normen: ["§ 307 BGB", "§ 308 BGB", "§ 309 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann ist Aufrechnung ausgeschlossen?", normen: ["§ 387 BGB", "§ 390 BGB", "§ 393 BGB"], prioritaet: "mittel" },
  { fach: "schuld", titel: "Was ist die Einrede des nicht erfüllten Vertrages?", normen: ["§ 320 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann führt eine Störung der Geschäftsgrundlage zur Anpassung, wann zur Auflösung?", normen: ["§ 313 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wie wirkt sich ein Rücktritt auf bereits erbrachte Leistungen aus?", normen: ["§ 346 BGB", "§ 347 BGB"], prioritaet: "hoch" },
  { fach: "schuld", titel: "Wann muss der Rücktrittsgegner Wertersatz leisten?", normen: ["§ 346 Abs. 2 BGB", "§ 346 Abs. 3 BGB"], prioritaet: "mittel" },

  /* ---- Schuldrecht BT ---------------------------------------------------- */
  { fach: "schuldbt", titel: "Wie prüft man den Sachmangel beim Kauf?", normen: ["§ 434 BGB", "§ 437 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Was hat sich mit dem subjektiven und objektiven Mangelbegriff geändert?", normen: ["§ 434 Abs. 2 BGB", "§ 434 Abs. 3 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wer trägt die Beweislast für einen Mangel und wann kehrt sie sich um?", normen: ["§ 477 BGB", "§ 363 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Was ist der Nacherfüllungsanspruch und wer bestimmt die Art?", normen: ["§ 439 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wer trägt die Aus- und Einbaukosten beim Mangel?", normen: ["§ 439 Abs. 3 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Wann ist der Rücktritt wegen Unerheblichkeit ausgeschlossen?", normen: ["§ 323 Abs. 5 S. 2 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Wie prüft man den Werkvertrag auf Mängel?", normen: ["§ 633 BGB", "§ 634 BGB", "§ 640 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Welche Bedeutung hat die Abnahme beim Werkvertrag?", normen: ["§ 640 BGB", "§ 644 BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wann darf der Mieter die Miete mindern?", normen: ["§ 536 BGB", "§ 536b BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wann ist eine Eigenbedarfskündigung wirksam?", normen: ["§ 573 Abs. 2 Nr. 2 BGB", "§ 573c BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Wie sind Schönheitsreparaturklauseln im Mietrecht zu beurteilen?", normen: ["§ 535 BGB", "§ 307 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Was ist der Unterschied zwischen Darlehen und Sachdarlehen?", normen: ["§ 488 BGB", "§ 607 BGB"], prioritaet: "selten" },
  { fach: "schuldbt", titel: "Wie prüft man den Auftrag und die Geschäftsbesorgung?", normen: ["§ 662 BGB", "§ 675 BGB"], prioritaet: "mittel" },
  { fach: "schuldbt", titel: "Welche Rechte hat der Verbraucher beim Widerruf?", normen: ["§ 355 BGB", "§ 357 BGB", "§ 312g BGB"], prioritaet: "hoch" },
  { fach: "schuldbt", titel: "Wann ist ein Reisemangel gegeben und was folgt daraus?", normen: ["§ 651i BGB", "§ 651m BGB"], prioritaet: "selten" },
  { fach: "schuldbt", titel: "Wie haftet der Schenker?", normen: ["§ 521 BGB", "§ 523 BGB", "§ 528 BGB"], prioritaet: "mittel" },

  /* ---- Gesetzliche Schuldverhältnisse ------------------------------------ */
  { fach: "gesetzs", titel: "Wie prüft man die berechtigte Geschäftsführung ohne Auftrag?", normen: ["§ 677 BGB", "§ 683 BGB", "§ 670 BGB"], prioritaet: "hoch" },
  { fach: "gesetzs", titel: "Was ist eine auch-fremde Geschäftsführung und ist sie GoA?", normen: ["§ 677 BGB"], prioritaet: "hoch",
    kern: { lernziele: ["Rechtsprechung: Fremdgeschäftsführungswille wird vermutet", "Literatur: reine Eigengeschäftsführung, GoA scheidet aus"] } },
  { fach: "gesetzs", titel: "Was folgt aus einer unberechtigten GoA?", normen: ["§ 684 BGB", "§ 812 BGB"], prioritaet: "mittel" },
  { fach: "gesetzs", titel: "Wie prüft man das Eigentümer-Besitzer-Verhältnis?", normen: ["§ 987 BGB", "§ 990 BGB", "§ 994 BGB"], prioritaet: "hoch" },
  { fach: "gesetzs", titel: "Welche Verwendungen sind notwendig und welche nützlich?", normen: ["§ 994 BGB", "§ 996 BGB"], prioritaet: "mittel" },
  { fach: "gesetzs", titel: "Was ist der Fremdbesitzerexzess?", normen: ["§ 991 Abs. 2 BGB", "§ 993 BGB"], prioritaet: "hoch" },

  /* ---- Bereicherungsrecht ------------------------------------------------ */
  { fach: "bereich", titel: "Wie prüft man die Leistungskondiktion?", normen: ["§ 812 Abs. 1 S. 1 Alt. 1 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Wann greift die Nichtleistungskondiktion?", normen: ["§ 812 Abs. 1 S. 1 Alt. 2 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Was ist der Vorrang der Leistungsbeziehung?", normen: ["§ 812 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Wie löst man den Dreiecksfall der Anweisung bereicherungsrechtlich?", normen: ["§ 812 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Was ist die Zweckverfehlungskondiktion?", normen: ["§ 812 Abs. 1 S. 2 Alt. 2 BGB"], prioritaet: "mittel" },
  { fach: "bereich", titel: "Wann ist die Kondiktion nach § 817 S. 2 BGB gesperrt?", normen: ["§ 817 BGB"], prioritaet: "mittel" },
  { fach: "bereich", titel: "Wann kann sich der Bereicherungsschuldner auf Entreicherung berufen?", normen: ["§ 818 Abs. 3 BGB", "§ 819 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Was ist die verschärfte Haftung nach § 819 BGB?", normen: ["§ 818 Abs. 4 BGB", "§ 819 BGB"], prioritaet: "mittel" },
  { fach: "bereich", titel: "Wie funktioniert die Eingriffskondiktion?", normen: ["§ 812 Abs. 1 S. 1 Alt. 2 BGB"], prioritaet: "hoch" },
  { fach: "bereich", titel: "Was ist eine Rückgriffskondiktion?", normen: ["§ 812 BGB", "§ 267 BGB"], prioritaet: "mittel" },

  /* ---- Sachenrecht ------------------------------------------------------- */
  { fach: "sachen", titel: "Wie prüft man die Übereignung nach § 929 S. 1 BGB?", normen: ["§ 929 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wann liegt ein Besitzkonstitut vor?", normen: ["§ 930 BGB", "§ 868 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie funktioniert die Übereignung durch Abtretung des Herausgabeanspruchs?", normen: ["§ 931 BGB", "§ 934 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Was ist ein Geheißerwerb?", normen: ["§ 929 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wann ist eine Sache abhandengekommen?", normen: ["§ 935 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie prüft man den gutgläubigen lastenfreien Erwerb?", normen: ["§ 936 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wie entsteht Eigentum durch Verbindung, Vermischung und Verarbeitung?", normen: ["§ 946 BGB", "§ 947 BGB", "§ 950 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wer ist Hersteller im Sinne des § 950 BGB?", normen: ["§ 950 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wie prüft man den Beseitigungs- und Unterlassungsanspruch?", normen: ["§ 1004 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wer ist Störer im Sinne des § 1004 BGB?", normen: ["§ 1004 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie funktioniert der Besitzschutz?", normen: ["§ 858 BGB", "§ 861 BGB", "§ 862 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Was ist der Unterschied zwischen unmittelbarem und mittelbarem Besitz?", normen: ["§ 854 BGB", "§ 868 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wie ist die Hypothek aufgebaut und wie unterscheidet sie sich von der Grundschuld?", normen: ["§ 1113 BGB", "§ 1191 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Was ist die Sicherungsgrundschuld und welche Einreden hat der Eigentümer?", normen: ["§ 1191 BGB", "§ 1157 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie funktioniert der Eigentumserwerb an Grundstücken?", normen: ["§ 873 BGB", "§ 925 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Was bewirkt eine Vormerkung?", normen: ["§ 883 BGB", "§ 888 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wie prüft man den Grundbuchberichtigungsanspruch?", normen: ["§ 894 BGB"], prioritaet: "mittel" },
  { fach: "sachen", titel: "Wann greift der öffentliche Glaube des Grundbuchs?", normen: ["§ 892 BGB", "§ 893 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Was ist der verlängerte Eigentumsvorbehalt?", normen: ["§ 449 BGB", "§ 398 BGB", "§ 185 BGB"], prioritaet: "hoch" },
  { fach: "sachen", titel: "Wann kollidieren Sicherungsübereignung und verlängerter Eigentumsvorbehalt?", normen: ["§ 930 BGB", "§ 398 BGB", "§ 138 BGB"], prioritaet: "hoch" },

  /* ---- Deliktsrecht ------------------------------------------------------ */
  { fach: "delikt", titel: "Wie prüft man § 823 Abs. 1 BGB?", normen: ["§ 823 Abs. 1 BGB"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Was ist ein Schutzgesetz im Sinne des § 823 Abs. 2 BGB?", normen: ["§ 823 Abs. 2 BGB"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Wann haftet man nach § 826 BGB?", normen: ["§ 826 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wie prüft man den Anspruch bei Verletzung des Eigentums durch Weiterfresserschaden?", normen: ["§ 823 Abs. 1 BGB"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Was gilt bei der Haftung mehrerer Schädiger?", normen: ["§ 830 BGB", "§ 840 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wann haften Aufsichtspflichtige für Kinder?", normen: ["§ 832 BGB", "§ 828 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wie funktioniert die Gefährdungshaftung nach dem StVG?", normen: ["§ 7 StVG", "§ 17 StVG", "§ 18 StVG"], prioritaet: "hoch" },
  { fach: "delikt", titel: "Wann ist ein Unfall ein unabwendbares Ereignis?", normen: ["§ 17 Abs. 3 StVG"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wie berechnet man Schmerzensgeld?", normen: ["§ 253 Abs. 2 BGB"], prioritaet: "mittel" },
  { fach: "delikt", titel: "Wann besteht ein Anspruch auf Ersatz des Nutzungsausfalls?", normen: ["§ 249 BGB"], prioritaet: "mittel" },

  /* ---- Arbeits-, Familien-, Erb-, Handels- und Gesellschaftsrecht --------- */
  { fach: "arbeit", titel: "Wie prüft man die betriebsbedingte Kündigung?", normen: ["§ 1 Abs. 2 KSchG", "§ 1 Abs. 3 KSchG"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wie funktioniert die Sozialauswahl?", normen: ["§ 1 Abs. 3 KSchG"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wann ist eine Abmahnung vor der Kündigung nötig?", normen: ["§ 314 Abs. 2 BGB", "§ 626 BGB"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Was ist die Kündigungsschutzklage und welche Frist gilt?", normen: ["§ 4 KSchG", "§ 7 KSchG"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wie haftet der Arbeitnehmer bei betrieblich veranlasster Tätigkeit?", normen: ["§ 619a BGB", "§ 254 BGB"], prioritaet: "hoch" },
  { fach: "arbeit", titel: "Wann ist eine Befristung ohne Sachgrund zulässig?", normen: ["§ 14 Abs. 2 TzBfG"], prioritaet: "mittel" },
  { fach: "arbeit", titel: "Welche Beteiligungsrechte hat der Betriebsrat bei einer Kündigung?", normen: ["§ 102 BetrVG"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wann besteht ein Anspruch auf Trennungsunterhalt?", normen: ["§ 1361 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wie ist die gesetzliche Erbfolge aufgebaut?", normen: ["§ 1924 BGB", "§ 1925 BGB", "§ 1931 BGB"], prioritaet: "hoch" },
  { fach: "famerb", titel: "Was gilt für ein gemeinschaftliches Testament?", normen: ["§ 2265 BGB", "§ 2270 BGB", "§ 2271 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wie funktioniert die Erbengemeinschaft?", normen: ["§ 2032 BGB", "§ 2038 BGB", "§ 2042 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wann kann man die Erbschaft ausschlagen?", normen: ["§ 1942 BGB", "§ 1944 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Wie haftet der Erbe für Nachlassverbindlichkeiten?", normen: ["§ 1967 BGB", "§ 1975 BGB", "§ 1990 BGB"], prioritaet: "mittel" },
  { fach: "famerb", titel: "Was ist ein Vermächtnis und wie wird es geltend gemacht?", normen: ["§ 2147 BGB", "§ 2174 BGB"], prioritaet: "mittel" },
  { fach: "handelsg", titel: "Wer ist Kaufmann und welche Arten gibt es?", normen: ["§ 1 HGB", "§ 2 HGB", "§ 5 HGB", "§ 6 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie funktioniert die Prokura?", normen: ["§ 48 HGB", "§ 49 HGB", "§ 50 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Was ist die kaufmännische Rügeobliegenheit?", normen: ["§ 377 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie wirkt das kaufmännische Bestätigungsschreiben?", normen: ["§ 346 HGB", "§ 242 BGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie prüft man den gutgläubigen Erwerb vom Kaufmann?", normen: ["§ 366 HGB", "§ 932 BGB"], prioritaet: "mittel" },
  { fach: "handelsg", titel: "Wie haftet der Kommanditist?", normen: ["§ 171 HGB", "§ 172 HGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wie entsteht die GmbH und was ist die Vor-GmbH?", normen: ["§ 11 GmbHG", "§ 13 GmbHG"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Wann haftet der Gesellschafter einer GmbH persönlich?", normen: ["§ 13 Abs. 2 GmbHG", "§ 826 BGB"], prioritaet: "hoch" },
  { fach: "handelsg", titel: "Was ist eine verdeckte Sacheinlage?", normen: ["§ 19 Abs. 4 GmbHG"], prioritaet: "mittel" },
  { fach: "handelsg", titel: "Wie werden Gesellschafterbeschlüsse angefochten?", normen: ["§ 47 GmbHG", "§ 243 AktG"], prioritaet: "mittel" },
  { fach: "handelsg", titel: "Was ist die actio pro socio?", normen: ["§ 705 BGB"], prioritaet: "mittel" },

  /* ---- ZPO --------------------------------------------------------------- */
  { fach: "zpo", titel: "Wie prüft man die Zulässigkeit einer Klage?", normen: ["§ 253 ZPO", "§ 12 ZPO", "§ 23 GVG"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wann ist das Gericht örtlich zuständig?", normen: ["§ 12 ZPO", "§ 13 ZPO", "§ 29 ZPO", "§ 32 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Was ist der Streitgegenstand und warum entscheidet er über die Rechtskraft?", normen: ["§ 253 ZPO", "§ 322 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wie weit reicht die materielle Rechtskraft?", normen: ["§ 322 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wann ist ein Feststellungsinteresse gegeben?", normen: ["§ 256 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wie funktioniert die Streitverkündung?", normen: ["§ 72 ZPO", "§ 74 ZPO", "§ 68 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Was ist eine Nebenintervention?", normen: ["§ 66 ZPO", "§ 67 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wie verteilt sich die Darlegungs- und Beweislast?", normen: ["§ 138 ZPO", "§ 286 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Was ist ein Anscheinsbeweis?", normen: ["§ 286 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wann ist neuer Vortrag in zweiter Instanz zuzulassen?", normen: ["§ 531 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wie wirkt eine Erledigung der Hauptsache?", normen: ["§ 91a ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Was ist der Unterschied zwischen Arrest und einstweiliger Verfügung?", normen: ["§ 916 ZPO", "§ 935 ZPO", "§ 940 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wie funktioniert die Vollstreckungsabwehrklage?", normen: ["§ 767 ZPO"], prioritaet: "hoch" },
  { fach: "zpo", titel: "Wie wird eine Forderung gepfändet?", normen: ["§ 829 ZPO", "§ 835 ZPO"], prioritaet: "mittel" },
  { fach: "zpo", titel: "Wie läuft das Mahnverfahren?", normen: ["§ 688 ZPO", "§ 700 ZPO"], prioritaet: "selten" },

  /* ---- Strafrecht AT ----------------------------------------------------- */
  { fach: "strafat", titel: "Wie ist ein vorsätzliches Begehungsdelikt aufgebaut?", normen: ["§ 13 StGB", "§ 15 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man die objektive Zurechnung?", normen: ["§ 13 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist eine eigenverantwortliche Selbstgefährdung?", normen: ["§ 222 StGB", "§ 216 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man die Notwehr?", normen: ["§ 32 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wann ist Notwehr sozialethisch eingeschränkt?", normen: ["§ 32 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist die Notwehrprovokation?", normen: ["§ 32 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man den entschuldigenden Notstand?", normen: ["§ 35 StGB"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Was ist ein Verbotsirrtum und wann ist er vermeidbar?", normen: ["§ 17 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man das Fahrlässigkeitsdelikt?", normen: ["§ 15 StGB", "§ 222 StGB", "§ 229 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist der Vertrauensgrundsatz im Straßenverkehr?", normen: ["§ 222 StGB", "§ 1 StVO"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Wie prüft man das unechte Unterlassungsdelikt?", normen: ["§ 13 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wann liegt Ingerenz vor?", normen: ["§ 13 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie grenzt man Tun und Unterlassen ab?", normen: ["§ 13 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wann beginnt das unmittelbare Ansetzen zum Versuch?", normen: ["§ 22 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie prüft man den Rücktritt bei mehreren Beteiligten?", normen: ["§ 24 Abs. 2 StGB"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Was ist ein fehlgeschlagener Versuch?", normen: ["§ 24 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wann liegt Mittäterschaft vor?", normen: ["§ 25 Abs. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist mittelbare Täterschaft und wann liegt ein Täter hinter dem Täter vor?", normen: ["§ 25 Abs. 1 Alt. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie wirkt der Exzess eines Mittäters?", normen: ["§ 25 Abs. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist eine notwendige Teilnahme?", normen: ["§ 26 StGB", "§ 27 StGB"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Wann liegt eine Anstiftung und wann psychische Beihilfe vor?", normen: ["§ 26 StGB", "§ 27 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie wirkt die Akzessorietät bei besonderen persönlichen Merkmalen?", normen: ["§ 28 StGB", "§ 29 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Wie unterscheidet man Tateinheit und Tatmehrheit?", normen: ["§ 52 StGB", "§ 53 StGB"], prioritaet: "hoch" },
  { fach: "strafat", titel: "Was ist eine mitbestrafte Nachtat?", normen: ["§ 52 StGB"], prioritaet: "mittel" },
  { fach: "strafat", titel: "Wie prüft man den dolus generalis?", normen: ["§ 16 StGB"], prioritaet: "mittel" },

  /* ---- Strafrecht BT ----------------------------------------------------- */
  { fach: "strafbt", titel: "Wie prüft man den Totschlag?", normen: ["§ 212 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was sind niedrige Beweggründe?", normen: ["§ 211 Abs. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann liegt Verdeckungsabsicht vor?", normen: ["§ 211 Abs. 2 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man die Körperverletzung mit Todesfolge?", normen: ["§ 227 StGB", "§ 18 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist eine Einwilligung in die Körperverletzung sittenwidrig?", normen: ["§ 228 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man die Nötigung und was ist Verwerflichkeit?", normen: ["§ 240 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist eine Freiheitsberaubung vollendet?", normen: ["§ 239 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie prüft man die Erpressung?", normen: ["§ 253 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist der Gewahrsamsbegriff beim Diebstahl?", normen: ["§ 242 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann liegt ein Gewahrsamsbruch trotz Einverständnis vor?", normen: ["§ 242 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man den besonders schweren Fall des Diebstahls?", normen: ["§ 243 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist ein Wohnungseinbruchdiebstahl gegeben?", normen: ["§ 244 Abs. 1 Nr. 3 StGB", "§ 244 Abs. 4 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Was ist ein gefährliches Werkzeug im Sinne des § 244 StGB?", normen: ["§ 244 Abs. 1 Nr. 1 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man die Unterschlagung und was ist die Zueignung?", normen: ["§ 246 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist eine Täuschung durch konkludentes Verhalten beim Betrug?", normen: ["§ 263 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann liegt eine Vermögensverfügung vor und wie grenzt man sie vom Diebstahl ab?", normen: ["§ 263 StGB", "§ 242 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist ein Dreiecksbetrug?", normen: ["§ 263 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man den Eingehungs- und den Erfüllungsbetrug?", normen: ["§ 263 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Was ist der Computerbetrug?", normen: ["§ 263a StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie unterscheidet man Missbrauchs- und Treubruchtatbestand der Untreue?", normen: ["§ 266 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist eine Urkunde zusammengesetzt?", normen: ["§ 267 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie prüft man die Sachbeschädigung?", normen: ["§ 303 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Was ist Hehlerei und wann liegt sie vor?", normen: ["§ 259 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wie prüft man die Begünstigung und die Strafvereitelung?", normen: ["§ 257 StGB", "§ 258 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie ist die Brandstiftung aufgebaut?", normen: ["§ 306 StGB", "§ 306a StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wann liegt eine Gefährdung des Straßenverkehrs vor?", normen: ["§ 315c StGB", "§ 316 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie prüft man das unerlaubte Entfernen vom Unfallort?", normen: ["§ 142 StGB"], prioritaet: "hoch" },
  { fach: "strafbt", titel: "Wann ist eine Aussage falsch im Sinne der §§ 153 ff. StGB?", normen: ["§ 153 StGB", "§ 154 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Wie prüft man Beleidigungsdelikte?", normen: ["§ 185 StGB", "§ 186 StGB", "§ 193 StGB"], prioritaet: "mittel" },
  { fach: "strafbt", titel: "Was ist eine Amtsträgereigenschaft und wann liegt Bestechlichkeit vor?", normen: ["§ 11 StGB", "§ 331 StGB", "§ 332 StGB"], prioritaet: "mittel" },

  /* ---- StPO -------------------------------------------------------------- */
  { fach: "stpo", titel: "Wie ist der Gang des Ermittlungsverfahrens?", normen: ["§ 152 StPO", "§ 160 StPO", "§ 170 StPO"], prioritaet: "mittel" },
  { fach: "stpo", titel: "Welche Rechte hat der Beschuldigte bei der Vernehmung?", normen: ["§ 136 StPO", "§ 163a StPO"], prioritaet: "hoch" },
  { fach: "stpo", titel: "Was folgt aus einem Verstoß gegen die Belehrungspflicht?", normen: ["§ 136 StPO", "§ 136a StPO"], prioritaet: "hoch" },
  { fach: "stpo", titel: "Wann besteht ein Zeugnisverweigerungsrecht?", normen: ["§ 52 StPO", "§ 53 StPO"], prioritaet: "mittel" },
  { fach: "stpo", titel: "Wie funktioniert die Beweisantragsrecht in der Hauptverhandlung?", normen: ["§ 244 Abs. 3 StPO"], prioritaet: "mittel" },
  { fach: "stpo", titel: "Was ist die Verständigung im Strafverfahren?", normen: ["§ 257c StPO"], prioritaet: "mittel" },
  { fach: "stpo", titel: "Wann darf vorläufig festgenommen werden?", normen: ["§ 127 StPO"], prioritaet: "mittel" },
  { fach: "stpo", titel: "Was ist der Unterschied zwischen Berufung und Revision?", normen: ["§ 312 StPO", "§ 333 StPO", "§ 337 StPO"], prioritaet: "hoch" },

  /* ---- Staatsrecht und Grundrechte --------------------------------------- */
  { fach: "staat", titel: "Wie prüft man die abstrakte Normenkontrolle?", normen: ["Art. 93 Abs. 1 Nr. 2 GG", "§ 76 BVerfGG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wann ist eine konkrete Normenkontrolle zulässig?", normen: ["Art. 100 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wie funktioniert das Bund-Länder-Streitverfahren?", normen: ["Art. 93 Abs. 1 Nr. 3 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Wie kommt ein Bundesgesetz zustande?", normen: ["Art. 76 GG", "Art. 77 GG", "Art. 78 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wann ist ein Gesetz zustimmungsbedürftig?", normen: ["Art. 84 GG", "Art. 104a GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wie weit reicht das Zitiergebot?", normen: ["Art. 19 Abs. 1 S. 2 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Was ist die Wesentlichkeitstheorie?", normen: ["Art. 20 Abs. 3 GG"], prioritaet: "hoch" },
  { fach: "staat", titel: "Wann darf der Bundestag aufgelöst werden?", normen: ["Art. 68 GG", "Art. 63 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Welche Rechte hat ein Abgeordneter?", normen: ["Art. 38 Abs. 1 S. 2 GG", "Art. 46 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Wie funktioniert der Untersuchungsausschuss?", normen: ["Art. 44 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Was folgt aus dem Bundesstaatsprinzip für die Verwaltung?", normen: ["Art. 83 GG", "Art. 84 GG", "Art. 85 GG"], prioritaet: "mittel" },
  { fach: "staat", titel: "Was ist die Ewigkeitsgarantie?", normen: ["Art. 79 Abs. 3 GG"], prioritaet: "mittel" },
  { fach: "grundr", titel: "Wie prüft man ein Freiheitsgrundrecht?", normen: ["Art. 2 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wann ist die Menschenwürde verletzt?", normen: ["Art. 1 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Was schützt das allgemeine Persönlichkeitsrecht?", normen: ["Art. 2 Abs. 1 GG", "Art. 1 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie prüft man die Versammlungsfreiheit?", normen: ["Art. 8 GG", "§ 15 VersG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wann ist eine Versammlung friedlich?", normen: ["Art. 8 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie löst man den Konflikt zwischen Meinungsfreiheit und Persönlichkeitsrecht?", normen: ["Art. 5 Abs. 1 GG", "Art. 2 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Was ist ein allgemeines Gesetz im Sinne des Art. 5 Abs. 2 GG?", normen: ["Art. 5 Abs. 2 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Wie weit reicht die Kunstfreiheit?", normen: ["Art. 5 Abs. 3 GG"], prioritaet: "mittel" },
  { fach: "grundr", titel: "Wie prüft man die Glaubensfreiheit?", normen: ["Art. 4 GG"], prioritaet: "mittel" },
  { fach: "grundr", titel: "Was schützt Art. 14 GG und wann liegt eine Enteignung vor?", normen: ["Art. 14 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Was ist eine ausgleichspflichtige Inhaltsbestimmung?", normen: ["Art. 14 Abs. 1 S. 2 GG"], prioritaet: "mittel" },
  { fach: "grundr", titel: "Wie prüft man Art. 6 GG?", normen: ["Art. 6 GG"], prioritaet: "mittel" },
  { fach: "grundr", titel: "Wann sind Grundrechte für Ausländer und juristische Personen anwendbar?", normen: ["Art. 19 Abs. 3 GG", "Art. 2 Abs. 1 GG"], prioritaet: "hoch" },
  { fach: "grundr", titel: "Was ist die Schutzpflichtdimension der Grundrechte?", normen: ["Art. 1 Abs. 1 S. 2 GG", "Art. 2 Abs. 2 GG"], prioritaet: "hoch" },

  /* ---- Verwaltungsrecht -------------------------------------------------- */
  { fach: "verwalt", titel: "Wie prüft man die Rechtmäßigkeit eines Verwaltungsakts?", normen: ["§ 35 VwVfG", "§ 40 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann ist ein Verwaltungsakt formell rechtswidrig und wann heilbar?", normen: ["§ 45 VwVfG", "§ 46 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann muss angehört werden?", normen: ["§ 28 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Welche Nebenbestimmungen gibt es und wie greift man sie an?", normen: ["§ 36 VwVfG", "§ 42 VwGO"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wie unterscheidet man gebundene Entscheidung und Ermessen?", normen: ["§ 40 VwVfG", "§ 114 VwGO"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Was ist eine Ermessensreduzierung auf null?", normen: ["§ 40 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann liegt ein unbestimmter Rechtsbegriff mit Beurteilungsspielraum vor?", normen: ["§ 114 VwGO"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wie funktioniert der Widerruf eines rechtmäßigen Verwaltungsakts?", normen: ["§ 49 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wann ist Vertrauensschutz zu gewähren?", normen: ["§ 48 Abs. 2 VwVfG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Was ist ein Verwaltungsakt mit Drittwirkung?", normen: ["§ 35 VwVfG", "§ 80a VwGO"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wie wirkt eine Zusicherung?", normen: ["§ 38 VwVfG"], prioritaet: "mittel" },
  { fach: "verwalt", titel: "Wann ist ein öffentlich-rechtlicher Vertrag nichtig?", normen: ["§ 59 VwVfG", "§ 56 VwVfG"], prioritaet: "mittel" },
  { fach: "verwalt", titel: "Was ist der Folgenbeseitigungsanspruch?", normen: ["Art. 20 Abs. 3 GG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Wie prüft man den Amtshaftungsanspruch?", normen: ["§ 839 BGB", "Art. 34 GG"], prioritaet: "hoch" },
  { fach: "verwalt", titel: "Was ist ein enteignungsgleicher Eingriff?", normen: ["Art. 14 GG"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Wie prüft man den Nachbarschutz im Baurecht?", normen: ["§ 31 Abs. 2 BauGB", "§ 34 BauGB"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wann ist eine Standardmaßnahme der Polizei zulässig?", normen: ["Polizeigesetze der Länder"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wie prüft man die Rechtmäßigkeit eines Platzverweises?", normen: ["Polizeigesetze der Länder"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Was ist der Unterschied zwischen Gefahrenabwehr und Strafverfolgung?", normen: ["§ 163 StPO", "Polizeigesetze der Länder"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wie funktioniert die unmittelbare Ausführung im Polizeirecht?", normen: ["Polizeigesetze der Länder"], prioritaet: "mittel" },
  { fach: "verwbt", titel: "Wann ist ein Bebauungsplan abwägungsfehlerhaft?", normen: ["§ 1 Abs. 7 BauGB", "§ 214 BauGB"], prioritaet: "hoch" },
  { fach: "verwbt", titel: "Wie funktioniert die Normenkontrolle gegen einen Bebauungsplan?", normen: ["§ 47 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wann ist der Verwaltungsrechtsweg eröffnet?", normen: ["§ 40 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wie prüft man die Klagebefugnis?", normen: ["§ 42 Abs. 2 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Was ist die Schutznormtheorie?", normen: ["§ 42 Abs. 2 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wann ist ein Vorverfahren erforderlich?", normen: ["§ 68 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Welche Fristen gelten für Widerspruch und Klage?", normen: ["§ 70 VwGO", "§ 74 VwGO", "§ 58 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wann entfällt die aufschiebende Wirkung?", normen: ["§ 80 Abs. 2 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wie prüft man den Antrag nach § 80 Abs. 5 VwGO?", normen: ["§ 80 Abs. 5 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Was gilt beim Rechtsschutz des Dritten gegen eine Baugenehmigung?", normen: ["§ 80a VwGO", "§ 212a BauGB"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Welcher Zeitpunkt ist für die Beurteilung der Sach- und Rechtslage maßgeblich?", normen: ["§ 113 VwGO"], prioritaet: "hoch" },
  { fach: "vwgo", titel: "Wie funktioniert die Beiladung?", normen: ["§ 65 VwGO"], prioritaet: "mittel" },
  { fach: "europa", titel: "Was ist der Anwendungsvorrang des Unionsrechts?", normen: ["Art. 4 Abs. 3 EUV"], prioritaet: "hoch" },
  { fach: "europa", titel: "Wie prüft man einen Verstoß gegen die Arbeitnehmerfreizügigkeit?", normen: ["Art. 45 AEUV"], prioritaet: "hoch" },
  { fach: "europa", titel: "Wann haftet ein Mitgliedstaat für die Verletzung von Unionsrecht?", normen: ["Art. 4 Abs. 3 EUV"], prioritaet: "mittel" },
  { fach: "europa", titel: "Wie funktioniert die Nichtigkeitsklage?", normen: ["Art. 263 AEUV"], prioritaet: "mittel" },
  { fach: "europa", titel: "Was ist die richtlinienkonforme Auslegung und wo endet sie?", normen: ["Art. 288 AEUV"], prioritaet: "hoch" },
  { fach: "europa", titel: "Wann gelten die Grundrechte der EU-Grundrechtecharta?", normen: ["Art. 51 GRCh"], prioritaet: "mittel" },
];
